Hey its a test commit
iamanh1990/movie-app-js pull request #1
Opened 2021-03-13 10:07 UTC by khanuxd

check it's working or not.

2021-03-13 10:14 UTC, iamanh1990 requested changes
Hey Finalize all codes and send it back.

2021-03-13 10:17 UTC, iamanh1990 requested changes

2021-03-13 10:17 UTC, iamanh1990 commented on src/assets/font/fontello.svg
> +<glyph glyph-name="git" unicode="&#xe800;" d="M0 3q0-63 62-108t150-45 151 45 62 108q0 64-62 109t-151 45q-1 0-3 0t-3-1q-24 22-24 48t24 53q71 4 120 55t49 121q0 28-7 50 28 5 44 14l0 115q-48-32-109-32l-7
Please change your naming classes

2021-03-14 14:16 UTC, khanuxd commented
Classes and IDs of HTML and CSS are fixed.

2021-03-14 14:19 UTC, closed without merging